## Importing and Organizing Your Data in Python - Part IV

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Import the 'example 01' file you created in the previous lecture and set the 'Date' column as an index of that table. 
Remember that there are two possible answers to this question.

In [1]:
import pandas

In [2]:
odebrane_dane = pandas.read_excel(r'C:\Users\Dom\Desktop\Moje\Python\Udemy\Python for Finance - Notebook Files\57 Importing Data - Part III\CSV\Python 3 CSV\example_01.xlsx')

In [5]:
odebrane_dane.set_index('Date')

                  AAPL        MSFT        XOM         BP
Date
2015-01-02  109.330002   46.759998  92.830002  38.119999
2015-01-05  106.250000   46.330002  90.290001  36.099998
2015-01-06  106.260002   45.650002  89.809998  35.830002
2015-01-07  107.750000   46.230000  90.720001  35.919998
2015-01-08  111.889999   47.590000  92.230003  36.730000
2015-01-09  112.010002   47.189999  92.099998  36.580002
2015-01-12  109.250000   46.599998  90.330002  36.049999
2015-01-13  110.220001   46.360001  90.000000  35.959999
2015-01-14  109.800003   45.959999  89.739998  35.669998
2015-01-15  106.820000   45.480000  88.959999  35.730000
2015-01-16  105.989998   46.240002  91.120003  37.860001
2015-01-20  108.720001   46.389999  91.089996  37.689999
2015-01-21  109.550003   45.919998  91.870003  38.820000
2015-01-22  112.400002   47.130001  92.870003  38.980000
2015-01-23  112.980003   47.180000  90.889999  38.900002
2015-01-26  113.099998   47.009998  91.760002  39.919998
2015-01-27  109.139999   42.660000  90.949997  40.209999
2015-01-28  115.309998   41.189999  87.949997  38.880001
2015-01-29  118.900002   42.009998  87.580002  38.750000
2015-01-30  117.160004   40.400002  87.419998  38.830002
2015-02-02  118.629997   41.279999  89.580002  39.860001
2015-02-03  118.650002   41.599998  92.250000  41.099998
2015-02-04  119.559998   41.840000  91.459999  40.450001
2015-02-05  119.940002   42.450001  92.360001  41.380001
2015-02-06  118.930000   42.410000  91.500000  41.169998
2015-02-09  119.720001   42.360001  91.559998  41.610001
2015-02-10  122.019997   42.599998  91.010002  41.250000
2015-02-11  124.879997   42.380001  90.599998  40.349998
2015-02-12  126.459999   43.090000  92.370003  41.340000
2015-02-13  127.080002   43.869999  93.370003  41.930000
...                ...         ...        ...        ...
2019-08-23  202.639999  133.389999  67.489998  36.209999
2019-08-26  206.490005  135.449997  67.849998  36.299999
2019-08-27  204.160004  135.740005  67.190002  36.599998
2019-08-28  205.529999  135.559998  67.680000  36.830002
2019-08-29  209.009995  138.119995  68.430000  36.950001
2019-08-30  208.740005  137.860001  68.480003  36.950001
2019-09-03  205.699997  136.039993  68.559998  36.950001
2019-09-04  209.190002  137.630005  69.290001  37.310001
2019-09-05  213.279999  140.050003  70.269997  37.369999
2019-09-06  213.259995  139.100006  70.930000  37.450001
2019-09-09  214.169998  137.520004  71.489998  37.500000
2019-09-10  216.699997  136.080002  72.070000  37.840000
2019-09-11  223.589996  136.119995  71.930000  37.799999
2019-09-12  223.089996  137.520004  71.980003  37.669998
2019-09-13  218.750000  137.320007  72.639999  37.869999
2019-09-16  219.899994  136.330002  73.730003  39.349998
2019-09-17  220.699997  137.389999  73.169998  38.540001
2019-09-18  222.770004  138.520004  72.820000  38.590000
2019-09-19  220.960007  141.070007  72.330002  38.689999
2019-09-20  217.729996  139.440002  72.080002  38.990002
2019-09-23  218.720001  139.139999  72.129997  38.759998
2019-09-24  217.679993  137.380005  71.139999  38.130001
2019-09-25  221.029999  139.360001  71.349998  38.169998
2019-09-26  219.889999  139.539993  70.970001  38.250000
2019-09-27  218.820007  137.729996  71.480003  38.259998
2019-09-30  223.970001  139.029999  70.610001  37.990002
2019-10-01  224.589996  137.070007  68.949997  37.700001
2019-10-02  218.960007  134.649994  67.150002  36.590000
2019-10-03  220.820007  136.279999  67.980003  36.369999
2019-10-04  226.320007  137.669998  68.379997  36.759998

[1198 rows x 4 columns]

In [6]:
odebrane_dane2 = pandas.read_excel(r'C:\Users\Dom\Desktop\Moje\Python\Udemy\Python for Finance - Notebook Files\57 Importing Data - Part III\CSV\Python 3 CSV\example_01.xlsx', index_col = 'Date')

In [7]:
odebrane_dane2

                  AAPL        MSFT        XOM         BP
Date
2015-01-02  109.330002   46.759998  92.830002  38.119999
2015-01-05  106.250000   46.330002  90.290001  36.099998
2015-01-06  106.260002   45.650002  89.809998  35.830002
2015-01-07  107.750000   46.230000  90.720001  35.919998
2015-01-08  111.889999   47.590000  92.230003  36.730000
2015-01-09  112.010002   47.189999  92.099998  36.580002
2015-01-12  109.250000   46.599998  90.330002  36.049999
2015-01-13  110.220001   46.360001  90.000000  35.959999
2015-01-14  109.800003   45.959999  89.739998  35.669998
2015-01-15  106.820000   45.480000  88.959999  35.730000
2015-01-16  105.989998   46.240002  91.120003  37.860001
2015-01-20  108.720001   46.389999  91.089996  37.689999
2015-01-21  109.550003   45.919998  91.870003  38.820000
2015-01-22  112.400002   47.130001  92.870003  38.980000
2015-01-23  112.980003   47.180000  90.889999  38.900002
2015-01-26  113.099998   47.009998  91.760002  39.919998
2015-01-27  109.139999   42.660000  90.949997  40.209999
2015-01-28  115.309998   41.189999  87.949997  38.880001
2015-01-29  118.900002   42.009998  87.580002  38.750000
2015-01-30  117.160004   40.400002  87.419998  38.830002
2015-02-02  118.629997   41.279999  89.580002  39.860001
2015-02-03  118.650002   41.599998  92.250000  41.099998
2015-02-04  119.559998   41.840000  91.459999  40.450001
2015-02-05  119.940002   42.450001  92.360001  41.380001
2015-02-06  118.930000   42.410000  91.500000  41.169998
2015-02-09  119.720001   42.360001  91.559998  41.610001
2015-02-10  122.019997   42.599998  91.010002  41.250000
2015-02-11  124.879997   42.380001  90.599998  40.349998
2015-02-12  126.459999   43.090000  92.370003  41.340000
2015-02-13  127.080002   43.869999  93.370003  41.930000
...                ...         ...        ...        ...
2019-08-23  202.639999  133.389999  67.489998  36.209999
2019-08-26  206.490005  135.449997  67.849998  36.299999
2019-08-27  204.160004  135.740005  67.190002  36.599998
2019-08-28  205.529999  135.559998  67.680000  36.830002
2019-08-29  209.009995  138.119995  68.430000  36.950001
2019-08-30  208.740005  137.860001  68.480003  36.950001
2019-09-03  205.699997  136.039993  68.559998  36.950001
2019-09-04  209.190002  137.630005  69.290001  37.310001
2019-09-05  213.279999  140.050003  70.269997  37.369999
2019-09-06  213.259995  139.100006  70.930000  37.450001
2019-09-09  214.169998  137.520004  71.489998  37.500000
2019-09-10  216.699997  136.080002  72.070000  37.840000
2019-09-11  223.589996  136.119995  71.930000  37.799999
2019-09-12  223.089996  137.520004  71.980003  37.669998
2019-09-13  218.750000  137.320007  72.639999  37.869999
2019-09-16  219.899994  136.330002  73.730003  39.349998
2019-09-17  220.699997  137.389999  73.169998  38.540001
2019-09-18  222.770004  138.520004  72.820000  38.590000
2019-09-19  220.960007  141.070007  72.330002  38.689999
2019-09-20  217.729996  139.440002  72.080002  38.990002
2019-09-23  218.720001  139.139999  72.129997  38.759998
2019-09-24  217.679993  137.380005  71.139999  38.130001
2019-09-25  221.029999  139.360001  71.349998  38.169998
2019-09-26  219.889999  139.539993  70.970001  38.250000
2019-09-27  218.820007  137.729996  71.480003  38.259998
2019-09-30  223.970001  139.029999  70.610001  37.990002
2019-10-01  224.589996  137.070007  68.949997  37.700001
2019-10-02  218.960007  134.649994  67.150002  36.590000
2019-10-03  220.820007  136.279999  67.980003  36.369999
2019-10-04  226.320007  137.669998  68.379997  36.759998

[1198 rows x 4 columns]