In [55]:
import numpy
import pandas
import pandas_datareader

In [57]:
import alpha_vantage

In [58]:
ts = alpha_vantage.timeseries.TimeSeries(key = '7S3IY9WAESC4P3EQ', output_format = 'pandas')

In [62]:
PG_av, metadata = ts.get_daily_adjusted('PG', outputsize = 'full')

In [63]:
PG_av

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient
date,,,,,,,,
1999-10-04,93.4380,96.5000,93.0630,96.250,28.2675,4495800.0,0.00,1.0
1999-10-05,95.5630,95.7500,93.8130,95.438,28.0289,4679800.0,0.00,1.0
1999-10-06,95.4380,97.3750,95.0000,97.063,28.5061,3868600.0,0.00,1.0
1999-10-07,97.3130,97.9380,96.6880,97.188,28.5428,2499400.0,0.00,1.0
1999-10-08,98.3750,99.0000,97.1880,98.063,28.7998,3100000.0,0.00,1.0
1999-10-11,98.0000,98.9380,97.5000,98.000,28.7815,2371600.0,0.00,1.0
1999-10-12,98.0000,98.0000,95.8750,97.188,28.5428,4270400.0,0.00,1.0
1999-10-13,97.3130,97.3130,95.0000,95.125,27.9371,3280000.0,0.00,1.0
1999-10-14,94.6880,96.8750,93.6880,95.813,28.1390,3714400.0,0.00,1.0
1999-10-15,95.7500,95.7500,93.3130,93.313,27.4048,5507000.0,0.00,1.0
1999-10-18,94.3750,95.8750,93.5630,95.313,27.9922,4544400.0,0.00,1.0
1999-10-19,96.2500,99.3130,96.0630,98.438,28.9099,5432000.0,0.00,1.0
1999-10-20,99.8750,99.8750,97.3750,99.563,29.3357,4500800.0,0.16,1.0
1999-10-21,99.1250,101.3750,98.6250,100.875,29.7224,4240400.0,0.00,1.0
1999-10-22,100.9380,101.3750,99.6880,100.750,29.6856,3812000.0,0.00,1.0
1999-10-25,99.1880,100.9060,98.5569,99.688,29.3725,2774000.0,0.00,1.0
1999-10-26,99.5630,100.2572,97.7500,98.188,28.9306,3307200.0,0.00,1.0
1999-10-27,97.6250,101.0000,97.3750,99.250,29.2436,5978400.0,0.00,1.0
1999-10-28,100.8750,104.9380,100.4875,104.625,30.8273,8669000.0,0.00,1.0
1999-10-29,104.3750,105.5000,104.1250,104.875,30.9010,7020000.0,0.00,1.0
1999-11-01,105.1199,108.6250,104.9380,108.000,31.8218,5621000.0,0.00,1.0
1999-11-02,107.7500,108.3750,106.0000,106.000,31.2325,5100200.0,0.00,1.0
1999-11-03,106.5630,107.6250,105.3130,106.750,31.4535,5006600.0,0.00,1.0
1999-11-04,107.2500,107.4383,104.0000,105.313,31.0299,4248000.0,0.00,1.0
1999-11-05,106.0000,106.8126,105.5000,105.875,31.1957,3306200.0,0.00,1.0
1999-11-08,105.8750,108.8130,105.6250,108.563,31.9875,3308600.0,0.00,1.0
1999-11-09,108.5630,108.6250,105.7500,107.500,31.6745,3014000.0,0.00,1.0
1999-11-10,107.5000,107.7500,105.6250,107.375,31.6376,2703600.0,0.00,1.0
1999-11-11,107.1250,107.7523,105.1250,106.438,31.3614,3446000.0,0.00,1.0
1999-11-12,106.5016,107.0000,105.4380,107.000,31.5271,3429400.0,0.00,1.0
...,...,...,...,...,...,...,...,...
2019-08-22,119.0800,119.7900,118.7000,119.420,119.4200,4558400.0,0.00,1.0
2019-08-23,119.1400,120.1100,116.4300,117.320,117.3200,7336800.0,0.00,1.0
2019-08-26,117.7500,119.6000,117.2200,119.320,119.3200,5661500.0,0.00,1.0
2019-08-27,119.9900,121.0500,119.7800,120.550,120.5500,6996300.0,0.00,1.0
2019-08-28,120.4600,121.4300,119.6300,121.400,121.4000,4600300.0,0.00,1.0
2019-08-29,121.7900,122.0000,120.3200,121.180,121.1800,5011500.0,0.00,1.0
2019-08-30,121.9600,122.0000,119.5100,120.230,120.2300,6007100.0,0.00,1.0
2019-09-03,119.7900,121.5400,119.6300,121.360,121.3600,4959300.0,0.00,1.0
2019-09-04,121.8500,123.2800,121.4600,123.210,123.2100,5586900.0,0.00,1.0
2019-09-05,123.2400,123.4300,122.1800,122.760,122.7600,7491900.0,0.00,1.0
2019-09-06,123.0000,123.3800,122.5400,122.870,122.8700,5306900.0,0.00,1.0
2019-09-09,122.7100,122.7800,121.7800,122.170,122.1700,7662400.0,0.00,1.0
2019-09-10,121.0300,121.1800,119.5800,119.880,119.8800,9582200.0,0.00,1.0
2019-09-11,119.8600,121.3400,119.3600,121.270,121.2700,7565500.0,0.00,1.0
2019-09-12,122.6500,123.2100,121.6200,122.770,122.7700,6194300.0,0.00,1.0
2019-09-13,121.8200,122.5800,121.5000,122.120,122.1200,6777400.0,0.00,1.0
2019-09-16,121.8100,121.9600,119.0200,119.750,119.7500,9626700.0,0.00,1.0
2019-09-17,119.6300,121.9900,119.4400,121.160,121.1600,6377100.0,0.00,1.0
2019-09-18,121.2700,121.9600,120.7700,121.410,121.4100,5684200.0,0.00,1.0
2019-09-19,121.3900,122.2300,121.2400,121.900,121.9000,4525800.0,0.00,1.0
2019-09-20,122.1300,122.6000,121.7500,122.240,122.2400,15362000.0,0.00,1.0
2019-09-23,122.2000,123.7700,121.9700,123.220,123.2200,6060400.0,0.00,1.0
2019-09-24,123.7000,124.7300,123.3600,123.610,123.6100,7633200.0,0.00,1.0
2019-09-25,123.5600,123.8300,122.9500,123.020,123.0200,5812600.0,0.00,1.0
2019-09-26,123.6400,125.0000,123.5300,124.310,124.3100,6984800.0,0.00,1.0
2019-09-27,124.4100,124.8800,123.7200,124.570,124.5700,5589800.0,0.00,1.0
2019-09-30,124.5700,125.3600,124.1300,124.380,124.3800,5206900.0,0.00,1.0
2019-10-01,124.3600,124.6400,123.2000,123.850,123.8500,5415700.0,0.00,1.0
2019-10-02,123.2000,123.6500,120.2100,121.080,121.0800,6755100.0,0.00,1.0
2019-10-03,121.6700,122.5400,120.8400,121.740,121.7400,4971763.0,0.00,1.0

In [64]:
metadata

{'1. Information': 'Daily Time Series with Splits and Dividend Events',
 '2. Symbol': 'PG',
 '3. Last Refreshed': '2019-10-03',
 '4. Output Size': 'Full size',
 '5. Time Zone': 'US/Eastern'}

In [66]:
ps = alpha_vantage.timeseries.TimeSeries(key = '7S3IY9WAESC4P3EQ', output_format = 'pandas')

In [81]:
help(alpha_vantage.timeseries.TimeSeries)

Help on class TimeSeries in module alpha_vantage.timeseries:

class TimeSeries(alpha_vantage.alphavantage.AlphaVantage)
 |  TimeSeries(key=None, output_format='json', treat_info_as_error=True, indexing_type='date', proxy=None)
 |
 |  This class implements all the api calls to times series
 |
 |  Method resolution order:
 |      TimeSeries
 |      alpha_vantage.alphavantage.AlphaVantage
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  get_batch_stock_quotes(self, symbols)
 |      Return multiple stock quotes with a single request.
 |      It raises ValueError when problems arise
 |
 |      Keyword Arguments:
 |          symbols:  A tuple or list Sof symbols to query
 |
 |  get_daily(self, symbol, outputsize='compact')
 |      Return daily time series in two json objects as data and
 |      meta_data. It raises ValueError when problems arise
 |
 |      Keyword Arguments:
 |          symbol:  the symbol for the equity we want to get its data
 |          outputsize:  The size of the call, supported values are
 |              'compact' and 'full; the first returns the last 100 points in the
 |              data series, and 'full' returns the full-length intraday times
 |              series, commonly above 1MB (default 'compact')
 |
 |  get_daily_adjusted(self, symbol, outputsize='compact')
 |      Return daily adjusted (date, daily open, daily high, daily low,
 |      daily close, daily split/dividend-adjusted close, daily volume)
 |      time series in two json objects as data and
 |      meta_data. It raises ValueError when problems arise
 |
 |      Keyword Arguments:
 |          symbol:  the symbol for the equity we want to get its data
 |          outputsize:  The size of the call, supported values are
 |              'compact' and 'full; the first returns the last 100 points in the
 |              data series, and 'full' returns the full-length intraday times
 |              series, commonly above 1MB (default 'compact')
 |
 |  get_intraday(self, symbol, interval='15min', outputsize='compact')
 |      Return intraday time series in two json objects as data and
 |      meta_data. It raises ValueError when problems arise
 |
 |      Keyword Arguments:
 |          symbol:  the symbol for the equity we want to get its data
 |          interval:  time interval between two conscutive values,
 |              supported values are '1min', '5min', '15min', '30min', '60min'
 |              (default '15min')
 |          outputsize:  The size of the call, supported values are
 |              'compact' and 'full; the first returns the last 100 points in the
 |              data series, and 'full' returns the full-length intraday times
 |              series, commonly above 1MB (default 'compact')
 |
 |  get_monthly(self, symbol)
 |      Return monthly time series in two json objects as data and
 |      meta_data. It raises ValueError when problems arise
 |
 |      Keyword Arguments:
 |          symbol:  the symbol for the equity we want to get its data
 |
 |  get_monthly_adjusted(self, symbol)
 |      Return monthly time series in two json objects as data and
 |      meta_data. It raises ValueError when problems arise
 |
 |      Keyword Arguments:
 |          symbol:  the symbol for the equity we want to get its data
 |
 |  get_quote_endpoint(self, symbol)
 |      Return the latest price and volume information for a
 |       security of your choice
 |
 |      Keyword Arguments:
 |          symbol:  the symbol for the equity we want to get its data
 |
 |  get_symbol_search(self, keywords)
 |      Return best matching symbols and market information
 |      based on keywords. It raises ValueError when problems arise
 |
 |      Keyword Arguments:
 |          keywords: the keywords to query on
 |
 |  get_weekly(self, symbol)
 |      Return weekly time series in two json objects as data and
 |      meta_data. It raises ValueError when problems arise
 |
 |      Keyword Arguments:
 |          symbol:  the symbol for the equity we want to get its data
 |
 |  get_weekly_adjusted(self, symbol)
 |      weekly adjusted time series (last trading day of each week,
 |      weekly open, weekly high, weekly low, weekly close, weekly adjusted
 |      close, weekly volume, weekly dividend) of the equity specified,
 |      covering up to 20 years of historical data.
 |      Keyword Arguments:
 |          symbol:  the symbol for the equity we want to get its data
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from alpha_vantage.alphavantage.AlphaVantage:
 |
 |  __init__(self, key=None, output_format='json', treat_info_as_error=True, indexing_type='date', proxy=None)
 |      Initialize the class
 |
 |      Keyword Arguments:
 |          key:  Alpha Vantage api key
 |          retries:  Maximum amount of retries in case of faulty connection or
 |              server not able to answer the call.
 |          treat_info_as_error: Treat information from the api as errors
 |          output_format:  Either 'json', 'pandas' os 'csv'
 |          indexing_type: Either 'date' to use the default date string given
 |          by the alpha vantage api call or 'integer' if you just want an
 |          integer indexing on your dataframe. Only valid, when the
 |          output_format is 'pandas'
 |          proxy: Dictionary mapping protocol or protocol and hostname to
 |          the URL of the proxy.
 |
 |  map_to_matype(self, matype)
 |      Convert to the alpha vantage math type integer. It returns an
 |      integer correspondent to the type of math to apply to a function. It
 |      raises ValueError if an integer greater than the supported math types
 |      is given.
 |
 |      Keyword Arguments:
 |          matype:  The math type of the alpha vantage api. It accepts
 |          integers or a string representing the math type.
 |
 |              * 0 = Simple Moving Average (SMA),
 |              * 1 = Exponential Moving Average (EMA),
 |              * 2 = Weighted Moving Average (WMA),
 |              * 3 = Double Exponential Moving Average (DEMA),
 |              * 4 = Triple Exponential Moving Average (TEMA),
 |              * 5 = Triangular Moving Average (TRIMA),
 |              * 6 = T3 Moving Average,
 |              * 7 = Kaufman Adaptive Moving Average (KAMA),
 |              * 8 = MESA Adaptive Moving Average (MAMA)
 |
 |  set_proxy(self, proxy=None)
 |      Set a new proxy configuration
 |
 |      Keyword Arguments:
 |          proxy: Dictionary mapping protocol or protocol and hostname to
 |          the URL of the proxy.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from alpha_vantage.alphavantage.AlphaVantage:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)

In [89]:
dane, metadata3 = ps.get_monthly_adjusted('PG')

In [90]:
dane

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount
date,,,,,,,
1999-11-30,105.1199,113.3130,104.0000,108.000,31.8218,84934200.0,0.000
1999-12-31,108.7500,115.6250,103.5000,109.563,32.2822,80968400.0,0.000
2000-01-31,107.8130,118.3750,94.8130,101.063,29.8594,181312400.0,0.160
2000-02-29,100.6880,100.8706,85.0000,87.875,25.9631,117475600.0,0.000
2000-03-31,88.0000,89.8130,52.7500,56.750,16.7670,579977000.0,0.000
2000-04-28,56.7500,72.7500,56.7500,59.750,17.7357,263464200.0,0.160
2000-05-31,59.8130,66.8750,58.7500,66.500,19.7393,132741200.0,0.000
2000-06-30,66.1250,66.3750,53.2500,56.750,16.8452,244567600.0,0.000
2000-07-31,56.7500,62.0000,54.1880,57.000,17.0217,165107000.0,0.175
2000-08-31,56.0000,64.5000,55.3750,61.832,18.4635,149902800.0,0.000
2000-09-29,61.6250,67.8130,60.0630,67.000,20.0079,177172600.0,0.000
2000-10-31,67.0630,76.9380,66.5630,71.438,21.4354,186260600.0,0.175
2000-11-30,70.8750,75.9380,67.1261,74.875,22.4669,140411400.0,0.000
2000-12-29,74.1250,79.3130,68.8750,78.438,23.5358,135825400.0,0.000
2001-01-31,78.1250,79.1880,66.7500,71.840,21.6616,152735200.0,0.175
2001-02-28,72.0000,77.1496,69.8500,70.500,21.2575,129571400.0,0.000
2001-03-30,70.0000,71.4000,59.2500,62.600,18.8755,160554000.0,0.000
2001-04-30,63.0000,63.6500,55.9600,60.050,18.2177,153575600.0,0.175
2001-05-31,62.8000,68.3000,62.2500,64.240,19.4888,144725200.0,0.000
2001-06-29,64.2300,66.3000,61.6800,63.800,19.3553,120983600.0,0.000
2001-07-31,64.0000,71.6000,63.7500,71.020,21.6634,123413400.0,0.190
2001-08-31,71.0300,77.2800,69.3600,74.150,22.6182,152829400.0,0.000
2001-09-28,73.6800,76.2400,67.0000,72.790,22.2033,142287200.0,0.000
2001-10-31,72.5000,74.4200,69.7300,73.780,22.6265,144373000.0,0.190
2001-11-30,73.8000,79.0000,73.6450,77.460,23.7551,116826200.0,0.000
2001-12-31,77.4500,81.7200,74.7600,79.130,24.2672,130743600.0,0.000
2002-01-31,78.9000,82.1200,76.3800,81.680,25.1693,128241600.0,0.190
2002-02-28,81.6800,87.8500,80.7500,84.790,26.1277,135382600.0,0.000
2002-03-28,85.0000,90.7330,82.6200,90.090,27.7608,137984200.0,0.000
2002-04-30,89.3500,92.7400,87.8526,90.260,27.9296,141148400.0,0.190
...,...,...,...,...,...,...,...
2017-05-31,87.3800,88.3500,85.5199,88.090,82.0290,138172700.0,0.000
2017-06-30,88.0200,90.2131,86.9300,87.150,81.1537,143596200.0,0.000
2017-07-31,87.4000,91.0700,86.3007,90.820,85.2347,122105100.0,0.690
2017-08-31,91.0300,92.9600,90.5200,92.270,86.5955,131332200.0,0.000
2017-09-29,92.4200,94.6700,90.3400,90.980,85.3848,138824900.0,0.000
2017-10-31,91.2600,93.5100,85.7200,86.340,81.6374,179372200.0,0.690
2017-11-30,86.3300,90.3698,85.4200,89.990,85.0886,123550900.0,0.000
2017-12-29,90.1800,93.1400,89.1200,91.880,86.8756,130696800.0,0.000
2018-01-31,91.9200,91.9300,86.0750,86.340,82.2597,190676000.0,0.690
2018-02-28,86.1500,86.5000,78.5000,78.520,74.8093,224924600.0,0.000
2018-03-29,78.4000,80.7450,75.8050,79.280,75.5334,211186000.0,0.000
2018-04-30,79.2600,79.5160,71.9500,72.340,69.5591,214265200.0,0.717
2018-05-31,72.0500,75.0150,70.7300,73.170,70.3572,184831100.0,0.000
2018-06-29,73.3300,78.7050,72.8600,78.060,75.0592,191430600.0,0.000
2018-07-31,77.4944,80.9800,77.4210,80.880,78.4767,167374200.0,0.717
2018-08-31,80.4200,84.2000,80.1100,82.950,80.4851,147692700.0,0.000
2018-09-28,82.4800,86.2800,81.2500,83.230,80.7568,137121300.0,0.000
2018-10-31,83.3100,90.7000,78.4900,88.680,86.8052,273769800.0,0.717
2018-11-30,88.8100,94.8016,88.1800,94.510,92.5119,214198200.0,0.000
2018-12-31,94.6700,96.8950,86.7400,91.920,89.9767,224359900.0,0.000
2019-01-31,91.0300,96.8100,89.0800,96.470,95.1774,225455800.0,0.717
2019-02-28,96.3500,100.4500,95.9900,98.550,97.2295,176165700.0,0.000
2019-03-29,98.6100,104.1500,97.7500,104.050,102.6558,180275300.0,0.000
2019-04-30,104.2300,107.2000,102.1300,106.480,105.7949,148284900.0,0.746
2019-05-31,106.1500,108.6800,102.4050,102.910,102.2478,139582600.0,0.000
2019-06-28,103.1500,112.6300,102.4000,109.650,108.9445,151126800.0,0.000
2019-07-31,109.9200,121.7600,109.6100,118.040,118.0400,166952300.0,0.746
2019-08-30,118.5600,122.0000,112.6800,120.230,120.2300,164651400.0,0.000
2019-09-30,119.7900,125.3600,119.0200,124.380,124.3800,139990300.0,0.000
2019-10-03,124.3600,124.6400,120.2100,121.740,121.7400,17142563.0,0.000

In [68]:
AAPL_av, metadata2 = ps.get_daily_adjusted('AAPL', outputsize = 'full')

In [80]:
help(get_daily_adjusted())

NameError: name 'get_daily_adjusted' is not defined

In [69]:
AAPL_av

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient
date,,,,,,,,
1999-10-04,62.3750,64.8750,62.3750,64.563,2.0123,114839200.0,0.0,1.0
1999-10-05,65.6250,68.1250,64.7500,67.938,2.1175,203551600.0,0.0,1.0
1999-10-06,69.3750,69.6250,67.0000,67.188,2.0941,201068000.0,0.0,1.0
1999-10-07,68.4380,68.6250,64.8750,66.375,2.0688,151471600.0,0.0,1.0
1999-10-08,66.1880,66.3130,63.5000,65.563,2.0435,95701200.0,0.0,1.0
1999-10-11,66.0000,68.2500,66.0000,66.688,2.0785,65780400.0,0.0,1.0
1999-10-12,67.8750,69.6200,67.0000,67.688,2.1097,140938000.0,0.0,1.0
1999-10-13,66.6250,69.5000,63.7500,64.031,1.9957,159182800.0,0.0,1.0
1999-10-14,69.2500,73.3130,69.0000,73.188,2.2811,474700800.0,0.0,1.0
1999-10-15,71.1250,75.8130,70.1880,74.563,2.3240,293294400.0,0.0,1.0
1999-10-18,73.8750,74.2500,71.1250,73.250,2.2831,194101600.0,0.0,1.0
1999-10-19,71.6250,75.0000,68.4380,68.500,2.1350,255645600.0,0.0,1.0
1999-10-20,70.0000,75.2500,70.0000,75.125,2.3415,270351200.0,0.0,1.0
1999-10-21,72.5627,77.0630,72.3750,76.125,2.3727,198363200.0,0.0,1.0
1999-10-22,77.1250,77.2500,73.3750,73.938,2.3045,104876800.0,0.0,1.0
1999-10-25,74.2500,76.1250,73.7485,74.500,2.3220,81648000.0,0.0,1.0
1999-10-26,74.9380,75.4992,73.3130,75.063,2.3396,90358800.0,0.0,1.0
1999-10-27,74.3750,76.6250,73.4380,76.375,2.3805,110768000.0,0.0,1.0
1999-10-28,77.0630,79.0000,76.0630,77.875,2.4272,126022400.0,0.0,1.0
1999-10-29,78.8130,81.0630,78.8130,80.125,2.4974,130762800.0,0.0,1.0
1999-11-01,80.0000,80.6880,77.3750,77.625,2.4194,69644400.0,0.0,1.0
1999-11-02,78.0000,81.6880,77.3130,80.250,2.5013,99808800.0,0.0,1.0
1999-11-03,81.6250,83.2500,81.0000,81.500,2.5402,82115600.0,0.0,1.0
1999-11-04,82.0630,85.3750,80.6250,83.625,2.6065,94771600.0,0.0,1.0
1999-11-05,84.6250,88.3750,84.0000,88.313,2.7526,104202000.0,0.0,1.0
1999-11-08,87.7500,97.7340,86.7500,96.375,3.0038,237731200.0,0.0,1.0
1999-11-09,94.3712,94.5000,88.0000,89.625,2.7935,202294400.0,0.0,1.0
1999-11-10,88.2500,93.2500,88.1250,91.438,2.8500,144474400.0,0.0,1.0
1999-11-11,91.5940,92.6250,89.8750,92.250,2.8753,67468800.0,0.0,1.0
1999-11-12,91.9380,92.0000,87.3738,90.625,2.8246,69764800.0,0.0,1.0
...,...,...,...,...,...,...,...,...
2019-08-22,213.1900,214.4400,210.7500,212.460,212.4600,22253700.0,0.0,1.0
2019-08-23,209.4300,212.0500,201.0000,202.640,202.6400,46818000.0,0.0,1.0
2019-08-26,205.8600,207.1900,205.0600,206.490,206.4900,26043600.0,0.0,1.0
2019-08-27,207.8600,208.5500,203.5300,204.160,204.1600,25873300.0,0.0,1.0
2019-08-28,204.1000,205.7200,203.3200,205.530,205.5300,15938800.0,0.0,1.0
2019-08-29,208.5000,209.3200,206.6600,209.010,209.0100,20990500.0,0.0,1.0
2019-08-30,210.1600,210.4500,207.2000,208.740,208.7400,21143400.0,0.0,1.0
2019-09-03,206.4300,206.9800,204.2200,205.700,205.7000,20023000.0,0.0,1.0
2019-09-04,208.3900,209.4800,207.3200,209.190,209.1900,19188100.0,0.0,1.0
2019-09-05,212.0000,213.9700,211.5100,213.280,213.2800,23913700.0,0.0,1.0
2019-09-06,214.0500,214.4200,212.5100,213.260,213.2600,19362300.0,0.0,1.0
2019-09-09,214.8400,216.4400,211.0700,214.170,214.1700,27309400.0,0.0,1.0
2019-09-10,213.8600,216.7800,211.7100,216.700,216.7000,31777900.0,0.0,1.0
2019-09-11,218.0700,223.7100,217.7300,223.590,223.5900,44289600.0,0.0,1.0
2019-09-12,224.8000,226.4200,222.8600,223.090,223.0900,32226700.0,0.0,1.0
2019-09-13,220.0000,220.7900,217.0200,218.750,218.7500,39763300.0,0.0,1.0
2019-09-16,217.7300,220.1300,217.5600,219.900,219.9000,21158100.0,0.0,1.0
2019-09-17,219.9600,220.8200,219.1200,220.700,220.7000,18318700.0,0.0,1.0
2019-09-18,221.0600,222.8500,219.4400,222.770,222.7700,25340000.0,0.0,1.0
2019-09-19,222.0100,223.7600,220.3700,220.960,220.9600,22060600.0,0.0,1.0
2019-09-20,221.3800,222.5600,217.4700,217.730,217.7300,55413100.0,0.0,1.0
2019-09-23,218.9500,219.8400,217.6500,218.720,218.7200,19165500.0,0.0,1.0
2019-09-24,221.0300,222.4900,217.1900,217.680,217.6800,31190800.0,0.0,1.0
2019-09-25,218.5500,221.5000,217.1400,221.030,221.0300,21903400.0,0.0,1.0
2019-09-26,220.0000,220.9400,218.8300,219.890,219.8900,18833500.0,0.0,1.0
2019-09-27,220.5400,220.9600,217.2800,218.820,218.8200,25352000.0,0.0,1.0
2019-09-30,220.9000,224.5800,220.7900,223.970,223.9700,25977400.0,0.0,1.0
2019-10-01,225.0700,228.2200,224.2000,224.590,224.5900,34805800.0,0.0,1.0
2019-10-02,223.0600,223.5800,217.9300,218.960,218.9600,34612300.0,0.0,1.0
2019-10-03,218.4300,220.9600,215.1320,220.820,220.8200,26496983.0,0.0,1.0

In [70]:
metadata2

{'1. Information': 'Daily Time Series with Splits and Dividend Events',
 '2. Symbol': 'AAPL',
 '3. Last Refreshed': '2019-10-03',
 '4. Output Size': 'Full size',
 '5. Time Zone': 'US/Eastern'}

In [71]:
type(ts)

alpha_vantage.timeseries.TimeSeries

In [74]:
type(AAPL_av)

pandas.core.frame.DataFrame

In [75]:
len(AAPL_av)

5033

In [1]:
import numpy as np
import pandas as pd

In [2]:
ser = pd.Series(np.random.random(5), name = "Column 01")

In [3]:
ser

0    0.649860
1    0.640622
2    0.022700
3    0.875074
4    0.393805
Name: Column 01, dtype: float64

In [4]:
ser[2]

0.022699937874711584

In [5]:
from pandas_datareader import data as wb

In [6]:
PG = wb.DataReader('PG', data_source='iex', start='2015-1-1')

5y

In [7]:
PG

               open     high      low    close    volume
date
2015-01-02  81.2074  81.3504  80.3849  80.8498   7255494
2015-01-05  80.6620  81.3504  80.3223  80.4654   8626143
2015-01-06  80.7336  80.9571  79.7949  80.0989   7791195
2015-01-07  80.4028  80.7872  80.0654  80.5190   5986899
2015-01-08  80.8855  81.5515  80.5727  81.4398   6831617
2015-01-09  81.5113  81.5113  80.5637  80.6799   4873097
2015-01-12  80.8811  81.0107  80.0139  80.3849   5250893
2015-01-13  81.1537  81.7974  80.2508  80.7246   6730752
2015-01-14  80.2151  80.5995  79.9480  80.4475   6418158
2015-01-15  80.8945  80.9034  79.8664  80.3313   6768180
2015-01-16  80.4117  81.6543  80.3402  81.5739   8815713
2015-01-20  81.5739  82.0566  80.9034  81.5202   9874638
2015-01-21  81.3885  82.0997  80.6952  81.6856   6974533
2015-01-22  81.9647  82.5499  80.9113  82.4868   7211231
2015-01-23  82.0817  82.0997  80.9833  81.1004   6745741
2015-01-26  80.9833  80.9833  79.8939  80.6502   9371693
2015-01-27  78.4174  78.5165  77.4451  77.8682  14417363
2015-01-28  77.9943  78.2464  76.5358  76.6618  14033420
2015-01-29  77.2290  77.5261  76.6618  77.1300  12054601
2015-01-30  76.6078  76.7289  75.8515  75.8875  14685250
2015-02-02  76.1486  76.6528  75.3383  76.6348  10278739
2015-02-03  77.3821  77.4271  76.6348  77.3821  10747897
2015-02-04  77.3280  77.8592  77.0219  77.2380   9212785
2015-02-05  77.6432  78.1293  77.5171  78.0573   6531298
2015-02-06  77.9313  77.9763  76.6618  77.0760   8429773
2015-02-09  76.8059  76.9139  76.1576  76.5718   8811512
2015-02-10  76.8239  77.0399  76.3647  76.8779   7059632
2015-02-11  77.3821  77.6071  76.6572  77.1030   7184577
2015-02-12  77.4811  77.5585  76.8959  77.4541   6074566
2015-02-13  77.4541  77.5621  76.9769  77.3370   6272049
...             ...      ...      ...      ...       ...
2018-05-03  70.8100  71.7200  70.7400  71.3600   9386498
2018-05-04  71.3800  72.6200  71.3400  72.4300   8107363
2018-05-07  72.6700  73.2200  71.8900  71.9800   6633579
2018-05-08  72.0500  72.1200  71.1110  71.4400   8084124
2018-05-09  71.7700  72.5450  71.7400  72.3700   7528359
2018-05-10  72.9400  73.3400  72.6900  73.1500   7618479
2018-05-11  73.6300  74.1000  73.0500  73.3700   7586194
2018-05-14  73.7800  73.7800  73.0900  73.2800   8646856
2018-05-15  73.3100  73.4100  72.6000  72.9500  11502785
2018-05-16  72.9800  73.9300  72.9600  73.5300   8324991
2018-05-17  73.5200  74.0000  73.4000  73.9600   8053611
2018-05-18  73.9800  74.0700  73.1100  73.4500   7042725
2018-05-21  73.7500  74.2500  73.4200  74.0600   6428395
2018-05-22  74.4600  74.9400  73.8300  74.0300   7744169
2018-05-23  74.0200  74.3000  73.7250  74.1800   6592494
2018-05-24  74.0800  74.3500  73.5929  73.7700   6508915
2018-05-25  73.9000  74.6200  73.7500  74.3100   7546467
2018-05-29  74.0600  74.7000  73.7700  74.0500   8905564
2018-05-30  74.3300  75.0150  74.0500  74.8900   8128645
2018-05-31  74.6700  74.6900  72.8000  73.1700  15525987
2018-06-01  73.3300  73.7350  72.8600  73.4500   7209292
2018-06-04  73.5400  74.6200  73.4500  74.1800   8743773
2018-06-05  74.2800  74.3752  73.6000  73.9700   6910144
2018-06-06  74.0700  74.4200  73.7200  74.3500   7002928
2018-06-07  74.1800  76.3939  74.1000  75.7600  13476090
2018-06-08  75.8500  77.2100  75.7400  77.1800  13625346
2018-06-11  76.9700  77.6900  76.8800  77.5300   9049393
2018-06-12  77.8200  77.8900  77.1100  77.2400   8786022
2018-06-13  77.4000  77.4000  76.2000  76.4700   8022397
2018-06-14  76.5600  76.5600  75.7000  75.9900   8895230

[869 rows x 5 columns]